services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: abcd
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scriptdb.sql:/docker-entrypoint-initdb.d/scriptdb.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 0
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgdata:
    name: pgdata
  pgadmin:
    name: pgadmin